version: '3.8'

services:
  # --- Контейнер Базы Данных ---
  db:
    image: postgres:15-alpine
    container_name: deribit_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432" # Если локально стоит Postgres, тогда порты оставляем так
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Контейнер Приложения (API + Worker) ---
  app:
    build: .
    container_name: deribit_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - REDIS_URL=${REDIS_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PYTHONPATH=/app

    ports:
      - "8000:8000"
    # Запускаем сразу API и в фоне Celery для экономии контейнеров
    command: sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 & celery -A app.celery_app worker --beat --loglevel=info -P solo --pidfile= --schedule=/tmp/celerybeat-schedule"

  # Redis для работы Celery
  redis:
    image: redis:7-alpine
    container_name: deribit_redis

volumes:
  postgres_data:
